[package]
name = "stenoedit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"

[[bin]]
edition = "2021"
name = "stenoedit"
path = "src/main.rs"

